export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     
      <body> <h1>This is root navbar</h1>
      {children}</body>
    </html>
  )
}
